import test from 'ava';

import { compileGlob, matchGlob } from '../file-glob.js';

test('compileGlob', t => {
  t.plan(12);
  const assertCompiles = glob => t.assert(typeof compileGlob(glob) === 'function');
  assertCompiles('');
  assertCompiles('a');
  assertCompiles('a/b');
  assertCompiles('a/b/c');
  assertCompiles('a,b');
  assertCompiles('a,b/c');
  assertCompiles('{a,b}');
  assertCompiles('a/{b,c}');
  assertCompiles('*');
  assertCompiles('*/*');
  assertCompiles('**');
  assertCompiles('a/{b/*,c/**}');
});

test('testGlob', t => {
  t.plan(99);
  const assertGlobTrue = (glob, target) => t.true(matchGlob(glob, target));
  const assertGlobFalse = (glob, target) => t.false(matchGlob(glob, target));
  assertGlobTrue('', '');
  assertGlobFalse('', 'a');
  assertGlobTrue('a', 'a');
  assertGlobFalse('a', '');
  assertGlobFalse('a', 'b');
  assertGlobFalse('a', 'ab');
  assertGlobFalse('a', 'ba');
  assertGlobFalse('a', 'bab');
  assertGlobTrue('a/b', 'a');
  assertGlobTrue('a/b', 'a/');
  assertGlobTrue('a/b', 'a/b');
  assertGlobTrue('a/b', 'a\\b');
  assertGlobTrue('a/b', 'a\\');
  assertGlobFalse('a/b', '');
  assertGlobFalse('a/b', 'b');
  assertGlobFalse('a/b', 'b/a');
  assertGlobFalse('a/b', 'a/b/');
  assertGlobFalse('a/b/c', '/b');
  assertGlobFalse('a/b/c', '\\b');
  assertGlobTrue('a/b/c', 'a');
  assertGlobTrue('a/b/c', 'a/');
  assertGlobTrue('a/b/c', 'a/b');
  assertGlobTrue('a/b/c', 'a/b/');
  assertGlobTrue('a/b/c', 'a\\b');
  assertGlobTrue('a/b/c', 'a\\b\\');
  assertGlobTrue('a/b/c', 'a/b/c');
  assertGlobTrue('a/b/c', 'a\\b\\c');
  assertGlobFalse('a/b/c', '');
  assertGlobFalse('a/b/c', 'b');
  assertGlobFalse('a/b/c', 'c');
  assertGlobFalse('a/b/c', 'b/c');
  assertGlobFalse('a/b/c', 'a/c');
  assertGlobTrue('a,b', 'a');
  assertGlobTrue('a,b', 'b');
  assertGlobFalse('a,b', '');
  assertGlobFalse('a,b', 'c');
  assertGlobFalse('a,b', 'ab');
  assertGlobTrue('a,b/c', 'a');
  assertGlobTrue('a,b/c', 'b');
  assertGlobTrue('a,b/c', 'b/c');
  assertGlobTrue('a,b/c', 'b\\c');
  assertGlobFalse('a,b/c', '');
  assertGlobFalse('a,b/c', 'a/');
  assertGlobFalse('a,b/c', 'b/c/');
  assertGlobFalse('a,b/c', 'a/c');
  assertGlobTrue('{a,b}', 'a');
  assertGlobTrue('{a,b}', 'b');
  assertGlobFalse('{a,b}', '');
  assertGlobFalse('{a,b}', 'c');
  assertGlobFalse('{a,b}', 'ab');
  assertGlobTrue('a/{b,c}', 'a');
  assertGlobTrue('a/{b,c}', 'a/b');
  assertGlobTrue('a/{b,c}', 'a\\b');
  assertGlobTrue('a/{b,c}', 'a');
  assertGlobTrue('a/{b,c}', 'a/c');
  assertGlobTrue('a/{b,c}', 'a\\c');
  assertGlobFalse('a/{b,c}', '');
  assertGlobFalse('a/{b,c}', 'b');
  assertGlobFalse('a/{b,c}', 'c');
  assertGlobFalse('a/{b,c}', 'b/c');
  assertGlobFalse('a/{b,c}', 'a/bc');
  assertGlobFalse('a/{b,c}', 'a/b/c');
  assertGlobTrue('*', 'a');
  assertGlobTrue('*', 'def');
  assertGlobFalse('*', '');
  assertGlobFalse('*', 'a/');
  assertGlobFalse('*', '/a');
  assertGlobFalse('*', 'a/b');
  assertGlobTrue('*/*', 'a');
  assertGlobTrue('*/*', 'a/');
  assertGlobTrue('*/*', 'a/b');
  assertGlobTrue('*/*', 'a/c');
  assertGlobTrue('*/*', 'def');
  assertGlobTrue('*/*', 'def/ghi');
  assertGlobFalse('*/*', '');
  assertGlobFalse('*/*', '/');
  assertGlobFalse('*/*', '/b');
  assertGlobFalse('*/*', 'a//b');
  assertGlobTrue('**', '');
  assertGlobTrue('**', 'def');
  assertGlobTrue('**', 'def/ghi');
  assertGlobTrue('**', 'def/');
  assertGlobTrue('**', '/ghi');
  assertGlobTrue('**', '/def/ghi/');
  assertGlobTrue('a/{b/*,c/**}', 'a');
  assertGlobTrue('a/{b/*,c/**}', 'a/b');
  assertGlobTrue('a/{b/*,c/**}', 'a/b/c');
  assertGlobTrue('a/{b/*,c/**}', 'a/b/def');
  assertGlobTrue('a/{b/*,c/**}', 'a/c');
  assertGlobTrue('a/{b/*,c/**}', 'a/c/b');
  assertGlobTrue('a/{b/*,c/**}', 'a/c/def');
  assertGlobTrue('a/{b/*,c/**}', 'a/c/def/ghi');
  assertGlobFalse('a/{b/*,c/**}', '');
  assertGlobFalse('a/{b/*,c/**}', 'a/d');
  assertGlobFalse('a/{b/*,c/**}', 'b');
  assertGlobFalse('a/{b/*,c/**}', 'b/');
  assertGlobFalse('a/{b/*,c/**}', 'c');
  assertGlobFalse('a/{b/*,c/**}', 'c/');
  assertGlobFalse('a/{b/*,c/**}', 'c/def');
});
